-- 0001_init.sql — canonical schema baseline for the Sancta Clinic Management System.
-- Runs identically on the clinic edge PostgreSQL and the managed cloud PostgreSQL
-- (ADR-0001/0002). Domains are separated into schemas (pack §14). This migration
-- establishes identity, flow, clinical, billing, inventory, finance, and the
-- cross-cutting security/sync/audit tables that every domain depends on.
--
-- Conventions (ADR-0006, pack §14.1): UUIDv7 primary keys generated by the app
-- offline; every business table carries the universal-field columns; balances are
-- derived from immutable movement/ledger tables, never stored as editable totals.

BEGIN;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS organisation;
CREATE SCHEMA IF NOT EXISTS scheduling;
CREATE SCHEMA IF NOT EXISTS flow;
CREATE SCHEMA IF NOT EXISTS clinical;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS security_sync;
CREATE SCHEMA IF NOT EXISTS audit;

-- ---------------------------------------------------------------------------
-- Universal-field domain types (pack §14.1). Applied as columns on every table.
-- ---------------------------------------------------------------------------
CREATE DOMAIN security_sync.sensitivity AS text
  CHECK (VALUE IN ('normal', 'sensitive', 'restricted'));

-- ---------------------------------------------------------------------------
-- security_sync: users, devices, sessions, outbox, sync checkpoints, conflicts
-- ---------------------------------------------------------------------------
CREATE TABLE security_sync.app_user (
  id              uuid PRIMARY KEY,
  username        text NOT NULL UNIQUE,
  display_name    text NOT NULL,
  status          text NOT NULL DEFAULT 'active',
  -- universal fields
  site_id         uuid,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  created_by      uuid,
  device_id       uuid,
  entity_version  integer NOT NULL DEFAULT 1,
  schema_version  integer NOT NULL DEFAULT 1
);

CREATE TABLE security_sync.device (
  id                uuid PRIMARY KEY,
  label             text NOT NULL,
  site_id           uuid,
  trust_state       text NOT NULL DEFAULT 'registered', -- registered | trusted | revoked
  last_sync_at      timestamptz,
  software_version  text,
  revoked_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- Encrypted outbox: written atomically with each business change (SYN-003).
CREATE TABLE security_sync.outbox_item (
  idempotency_key  text PRIMARY KEY,           -- dedup anchor end-to-end (NFR-010)
  entity_type      text NOT NULL,
  entity_id        uuid NOT NULL,
  entity_version   integer NOT NULL,
  origin_site      uuid NOT NULL,
  device_id        uuid NOT NULL,
  user_id          uuid NOT NULL,
  schema_version   integer NOT NULL,
  priority         integer NOT NULL DEFAULT 100,
  dependencies     text[] NOT NULL DEFAULT '{}',
  captured_at      timestamptz NOT NULL,       -- device clock (SYN-007)
  received_at      timestamptz,               -- authoritative clock, set on ingress
  sync_state       text NOT NULL DEFAULT 'queued', -- queued|transmitting|acknowledged|rejected|conflict|quarantined
  payload          jsonb NOT NULL
);
CREATE INDEX outbox_state_priority_idx ON security_sync.outbox_item (sync_state, priority, captured_at);

-- Applied idempotency keys on the receiving side — the DB guarantee behind
-- IdempotentApplier (idempotency.ts). A duplicate key is a no-op insert.
CREATE TABLE security_sync.applied_change (
  idempotency_key  text PRIMARY KEY,
  applied_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE security_sync.sync_checkpoint (
  site_id          uuid PRIMARY KEY,
  last_pulled_at   timestamptz,
  cursor           text
);

CREATE TABLE security_sync.conflict_case (
  id               uuid PRIMARY KEY,
  entity_type      text NOT NULL,
  entity_id        uuid NOT NULL,
  detected_at      timestamptz NOT NULL DEFAULT now(),
  status           text NOT NULL DEFAULT 'open', -- open | resolved
  local_version    jsonb NOT NULL,
  incoming_version jsonb NOT NULL,
  resolution       jsonb
);

-- ---------------------------------------------------------------------------
-- audit: tamper-evident events (BR-012, NFR-016). Append-only; no UPDATE/DELETE.
-- ---------------------------------------------------------------------------
CREATE TABLE audit.audit_event (
  id            uuid PRIMARY KEY,
  actor_user    uuid,
  actor_role    text,
  site_id       uuid,
  device_id     uuid,
  action        text NOT NULL,        -- view|create|amend|sign|approve|print|export|break_glass|search|login|config
  resource_type text NOT NULL,
  resource_id   uuid,
  patient_ref   uuid,                 -- protected from ordinary log viewers
  before_ver    integer,
  after_ver     integer,
  outcome       text NOT NULL,
  reason        text,
  purpose       text,
  captured_at   timestamptz NOT NULL, -- device time
  received_at   timestamptz NOT NULL DEFAULT now(),
  clock_drift   boolean NOT NULL DEFAULT false,
  -- hash chain for tamper evidence
  prev_hash     text,
  event_hash    text NOT NULL
);
CREATE INDEX audit_resource_idx ON audit.audit_event (resource_type, resource_id);
CREATE INDEX audit_patient_idx ON audit.audit_event (patient_ref);

-- ---------------------------------------------------------------------------
-- identity: durable patient master (PAT-001, BR-001/002)
-- ---------------------------------------------------------------------------
CREATE TABLE identity.patient (
  id               uuid PRIMARY KEY,            -- durable identity, distinct from visit/encounter
  mrn              text UNIQUE,                 -- human-readable, site-scoped
  given_name       text,
  family_name      text,
  date_of_birth    date,                        -- stored as a date, never age (BR-002)
  dob_estimated    boolean NOT NULL DEFAULT false,
  sex              text,
  phone            text,
  deceased         boolean NOT NULL DEFAULT false,
  sensitivity      security_sync.sensitivity NOT NULL DEFAULT 'normal',
  -- universal fields
  site_id          uuid,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  created_by       uuid,
  device_id        uuid,
  origin_site      uuid,
  entity_version   integer NOT NULL DEFAULT 1,
  schema_version   integer NOT NULL DEFAULT 1
);

CREATE TABLE identity.patient_merge (
  id               uuid PRIMARY KEY,
  surviving_id     uuid NOT NULL REFERENCES identity.patient(id),
  merged_id        uuid NOT NULL,               -- source identifier is preserved, not deleted (PAT-008)
  merged_at        timestamptz NOT NULL DEFAULT now(),
  merged_by        uuid NOT NULL,
  reversible       boolean NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------------
-- flow: visit + queue (VIS-001..008)
-- ---------------------------------------------------------------------------
CREATE TABLE flow.visit (
  id             uuid PRIMARY KEY,
  patient_id     uuid NOT NULL REFERENCES identity.patient(id),
  visit_number   text UNIQUE,
  site_id        uuid NOT NULL,
  status         text NOT NULL DEFAULT 'open',  -- see VISIT_TRANSITIONS
  opened_at      timestamptz NOT NULL DEFAULT now(),
  completed_at   timestamptz,
  entity_version integer NOT NULL DEFAULT 1
);

-- ---------------------------------------------------------------------------
-- clinical: encounter (append-only once signed — EHR-008/009, BR-003)
-- ---------------------------------------------------------------------------
CREATE TABLE clinical.encounter (
  id             uuid PRIMARY KEY,
  visit_id       uuid NOT NULL REFERENCES flow.visit(id),
  patient_id     uuid NOT NULL REFERENCES identity.patient(id),
  status         text NOT NULL DEFAULT 'draft', -- draft|ready_to_sign|signed|entered_in_error
  form_version   integer,
  signed_by      uuid,
  signed_at      timestamptz,
  content        jsonb NOT NULL DEFAULT '{}',
  entity_version integer NOT NULL DEFAULT 1,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE clinical.encounter_addendum (
  id             uuid PRIMARY KEY,
  encounter_id   uuid NOT NULL REFERENCES clinical.encounter(id),
  author         uuid NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  content        jsonb NOT NULL
);

-- ---------------------------------------------------------------------------
-- billing: fee versions, invoice, payment, allocation (BIL-*)
-- ---------------------------------------------------------------------------
CREATE TABLE billing.fee_version (
  service_code   text NOT NULL,
  version        integer NOT NULL,
  effective_from date NOT NULL,
  effective_to   date,
  standard_minor bigint NOT NULL,
  min_minor      bigint NOT NULL,
  max_minor      bigint NOT NULL,
  tax_rate_bps   integer,
  currency       text NOT NULL DEFAULT 'USD',
  PRIMARY KEY (service_code, version)
);

CREATE TABLE billing.invoice (
  id             uuid PRIMARY KEY,
  invoice_number text UNIQUE,
  patient_id     uuid NOT NULL REFERENCES identity.patient(id),
  status         text NOT NULL DEFAULT 'draft', -- see INVOICE_TRANSITIONS
  currency       text NOT NULL DEFAULT 'USD',
  finalised_at   timestamptz,
  entity_version integer NOT NULL DEFAULT 1,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE billing.invoice_line (
  id             uuid PRIMARY KEY,
  invoice_id     uuid NOT NULL REFERENCES billing.invoice(id),
  service_code   text NOT NULL,
  rule_version   integer NOT NULL,            -- applied fee version retained (BIL-001, BR-005)
  standard_minor bigint NOT NULL,
  applied_minor  bigint NOT NULL,
  adjustment_minor bigint NOT NULL DEFAULT 0,
  tax_minor      bigint NOT NULL DEFAULT 0,
  reason         text,
  approver       uuid
);

CREATE TABLE billing.payment (
  id             uuid PRIMARY KEY,
  receipt_number text UNIQUE,
  patient_id     uuid NOT NULL REFERENCES identity.patient(id),
  method         text NOT NULL,               -- cash|card|bank|mobile|voucher
  amount_minor   bigint NOT NULL,
  currency       text NOT NULL DEFAULT 'USD',
  status         text NOT NULL DEFAULT 'confirmed',
  received_at    timestamptz NOT NULL DEFAULT now()
);

-- Allocations are separate from payments (BIL-006, BR-006); reallocation appends.
CREATE TABLE billing.payment_allocation (
  id             uuid PRIMARY KEY,
  payment_id     uuid NOT NULL REFERENCES billing.payment(id),
  invoice_id     uuid NOT NULL REFERENCES billing.invoice(id),
  amount_minor   bigint NOT NULL,
  allocated_at   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- inventory: products, lots, immutable movements (INV-*, BR-007)
-- ---------------------------------------------------------------------------
CREATE TABLE inventory.product (
  sku            text PRIMARY KEY,
  name           text NOT NULL,
  category       text,
  base_unit      text NOT NULL,
  controlled     boolean NOT NULL DEFAULT false,
  reorder_min    integer,
  reorder_max    integer
);

CREATE TABLE inventory.lot (
  id             uuid PRIMARY KEY,
  sku            text NOT NULL REFERENCES inventory.product(sku),
  expiry_date    date NOT NULL,
  status         text NOT NULL DEFAULT 'available', -- available|quarantined|expired|recalled
  unit_cost_minor bigint NOT NULL,
  supplier       text
);

-- Append-only; balances are derived (BR-007). No UPDATE/DELETE in application code.
CREATE TABLE inventory.stock_movement (
  id             uuid PRIMARY KEY,
  sku            text NOT NULL REFERENCES inventory.product(sku),
  lot_id         uuid NOT NULL REFERENCES inventory.lot(id),
  location       text NOT NULL,
  movement_type  text NOT NULL,
  quantity       integer NOT NULL,           -- signed base units
  occurred_at    timestamptz NOT NULL DEFAULT now(),
  source_ref     text
);
CREATE INDEX stock_movement_lot_idx ON inventory.stock_movement (lot_id);
CREATE INDEX stock_movement_sku_idx ON inventory.stock_movement (sku);

-- Derived balance view — the ONLY sanctioned way to read on-hand quantity.
CREATE VIEW inventory.stock_balance AS
  SELECT sku, lot_id, location, sum(quantity)::bigint AS on_hand
  FROM inventory.stock_movement
  GROUP BY sku, lot_id, location;

-- ---------------------------------------------------------------------------
-- finance: chart of accounts + immutable journals (FIN-001/002, BR-009)
-- ---------------------------------------------------------------------------
CREATE TABLE finance.account (
  code           text PRIMARY KEY,
  name           text NOT NULL,
  type           text NOT NULL,               -- asset|liability|equity|revenue|expense
  active         boolean NOT NULL DEFAULT true
);

CREATE TABLE finance.financial_period (
  id             text PRIMARY KEY,            -- e.g. 2026-07
  status         text NOT NULL DEFAULT 'open', -- open|soft_close|hard_close
  opened_at      timestamptz NOT NULL DEFAULT now(),
  closed_at      timestamptz
);

CREATE TABLE finance.journal_batch (
  id             uuid PRIMARY KEY,
  origin         text NOT NULL,               -- system|manual
  source_type    text NOT NULL,
  source_id      text NOT NULL,
  currency       text NOT NULL DEFAULT 'USD',
  posting_date   date NOT NULL,
  period_id      text REFERENCES finance.financial_period(id),
  reverses       uuid REFERENCES finance.journal_batch(id),
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE finance.journal_line (
  id             uuid PRIMARY KEY,
  batch_id       uuid NOT NULL REFERENCES finance.journal_batch(id),
  account_code   text NOT NULL REFERENCES finance.account(code),
  debit_minor    bigint NOT NULL DEFAULT 0,
  credit_minor   bigint NOT NULL DEFAULT 0,
  cost_centre    text,
  memo           text,
  CHECK (debit_minor >= 0 AND credit_minor >= 0),
  CHECK (NOT (debit_minor > 0 AND credit_minor > 0))
);
CREATE INDEX journal_line_account_idx ON finance.journal_line (account_code);

COMMIT;
