#!/usr/bin/env node
/**
 * Backlog coverage dashboard. Reads docs/requirements/coverage.json and prints a
 * per-module table plus overall percentages, and writes docs/requirements/
 * COVERAGE.md. Keeps the "how much is done" number honest and self-updating:
 * partial items count as half. Run: `npm run coverage`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cov = JSON.parse(readFileSync(join(root, 'docs/requirements/coverage.json'), 'utf8'));

const prefixOf = (id) => id.split('-')[0];
const builtByModule = {};
const partialByModule = {};
for (const id of cov.built) (builtByModule[prefixOf(id)] ??= new Set()).add(id);
for (const id of cov.partial) (partialByModule[prefixOf(id)] ??= new Set()).add(id);

let fTotal = 0, fBuilt = 0, fPartial = 0;
const rows = [];
for (const [mod, total] of Object.entries(cov.moduleTotals)) {
  const b = (builtByModule[mod]?.size) ?? 0;
  const p = (partialByModule[mod]?.size) ?? 0;
  const weighted = b + p * 0.5;
  const pct = ((weighted / total) * 100).toFixed(0);
  rows.push({ mod, total, b, p, n: total - b - p, pct });
  fTotal += total; fBuilt += b; fPartial += p;
}

const pctOf = (b, p, t) => (((b + p * 0.5) / t) * 100).toFixed(1);
const fWeightedPct = pctOf(fBuilt, fPartial, fTotal);

const nfrBuilt = cov.nfrBuilt.length, nfrPartial = cov.nfrPartial.length;
const brBuilt = cov.brBuilt.length, brPartial = cov.brPartial.length;
const nfrPct = pctOf(nfrBuilt, nfrPartial, cov.nfrTotal);
const brPct = pctOf(brBuilt, brPartial, cov.brTotal);

const bar = (pct) => {
  const filled = Math.round((pct / 100) * 20);
  return '█'.repeat(filled) + '░'.repeat(20 - filled);
};

// --- console
console.log('\nSancta Clinic — backlog coverage\n');
console.log('Module  Total  Built  Partial  Not  %');
for (const r of rows) {
  console.log(
    `${r.mod.padEnd(6)} ${String(r.total).padStart(5)} ${String(r.b).padStart(6)} ${String(r.p).padStart(8)} ${String(r.n).padStart(4)}  ${r.pct}%`,
  );
}
console.log('-'.repeat(44));
console.log(`Functional  ${fTotal} total  built ${fBuilt}  partial ${fPartial}  => ${fWeightedPct}% ${bar(Number(fWeightedPct))}`);
console.log(`NFR         ${cov.nfrTotal} total  built ${nfrBuilt}  partial ${nfrPartial}  => ${nfrPct}% ${bar(Number(nfrPct))}`);
console.log(`Business rules ${cov.brTotal} total  built ${brBuilt}  partial ${brPartial}  => ${brPct}% ${bar(Number(brPct))}\n`);

// --- markdown
const md = `# Backlog coverage (generated)

> Generated by \`npm run coverage\` from \`coverage.json\`. Partial items count as half.
> Do not edit by hand — update \`coverage.json\` and re-run.

## Functional requirements — ${fWeightedPct}% weighted

| Module | Total | Built | Partial | Not started | % |
|--------|------:|------:|--------:|------------:|--:|
${rows.map((r) => `| ${r.mod} | ${r.total} | ${r.b} | ${r.p} | ${r.n} | ${r.pct}% |`).join('\n')}
| **Total** | **${fTotal}** | **${fBuilt}** | **${fPartial}** | **${fTotal - fBuilt - fPartial}** | **${fWeightedPct}%** |

## Non-functional requirements — ${nfrPct}% weighted

Built ${nfrBuilt}/${cov.nfrTotal}, partial ${nfrPartial}. Built: ${cov.nfrBuilt.join(', ')}.

## Business rules — ${brPct}% weighted

Built ${brBuilt}/${cov.brTotal}, partial ${brPartial}. Built: ${cov.brBuilt.join(', ')}.

## Headline

- **Functional backlog (breadth):** ${fWeightedPct}% weighted (${fBuilt} built + ${fPartial} partial of ${fTotal}).
- **Safety-critical business rules:** ${brPct}%.
- **Measurable NFRs:** ${nfrPct}%.

Coverage is deliberately deepest on the highest-risk foundations (offline-first
architecture, synchronisation, ledgers, atomic transactions) — see
\`verification-evidence.md\`.
`;
writeFileSync(join(root, 'docs/requirements/COVERAGE.md'), md);
console.log('Wrote docs/requirements/COVERAGE.md');
